version: "3.9"
services:
  fastapi:
    build: .
    container_name: fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    networks:
      - app_network2
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - app_network2

networks:
  app_network2:
    driver: bridge